version: '2.3'
services:
  tf:
    build: .
    image: kik/kik1
    runtime: nvidia
    privileged: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
    user: "1000:video"
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/tf/notebooks
      - /tmp/.X11-unix:/tmp/.X11-unix